export const MODULE_GA = 'ga'
export const MODULE_MIXPANEL = 'mixpanel'
export const MODULE_SEGMENT = 'segment'
export const MODULE_FACEBOOK = 'facebook'
export const MODULE_MPARTICLE = 'mparticle'
export const MODULE_AMPLITUDE = 'amplitude'
export const MODULE_FULLSTORY = 'fullstory'
export const MODULE_HUBSPOT = 'hubspot'